name: flutter_adaptive_cards
description: Adaptive Cards are platform-agnostic snippets of UI, authored in JSON, that apps and services can openly exchange.
version: 0.1.2
homepage: https://github.com/neohelden/Flutter-AdaptiveCards

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # General
  http: ^0.13.0
  provider: ^5.0.0
  uuid: ^2.2.2
  ## Localization
  intl: ^0.17.0
  ## Used for automatic color adjustment for dark theme
  tinycolor: ^1.0.3

  # Content
  ## Video player with controls
  chewie: ^0.12.0
  video_player: ^1.0.1
  ## Markdown renderer
  flutter_markdown: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.3
  mockito: ^4.1.3

flutter:
